#include "clock.h"

void clockInit(void){
	RCC->CFGR |= (((CPUFrq/4000000)-2)<<RCC_CFGR_PLLMUL_Pos);
	RCC->CFGR |= (RCC_CFGR_PPRE_0|RCC_CFGR_PPRE_2);
	RCC->CR |= RCC_CR_PLLON;
	while(!(RCC->CR&RCC_CR_PLLRDY));
	RCC->CFGR |= RCC_CFGR_SW_1;
	while(!(RCC->CFGR&RCC_CFGR_SWS_1));
	
	RCC->AHBENR |= RCC_AHBENR_GPIOAEN;
	RCC->AHBENR |= RCC_AHBENR_GPIOBEN;
	RCC->AHBENR |= RCC_AHBENR_GPIOCEN;
	RCC->AHBENR |= RCC_AHBENR_GPIODEN;
	RCC->AHBENR |= RCC_AHBENR_GPIOFEN;
	
	RCC->APB2ENR |= RCC_APB2ENR_USART1EN;
	RCC->APB2ENR |= RCC_APB2ENR_TIM1EN;
}
